---
- name: Create Azure User-Assigned Managed Identity
  hosts: localhost
  connection: local
  vars:
    resource_group_name: aro-rg
    #location: eastus
    #identity_name: userAssignedIdentities
    #identity_name: myUserAssignedIdentity
  tasks:
    - name: Create the user-assigned managed identity
      shell: az identity create --name "{{ res_name }}" --resource-group "{{ resource_group_name }}"
      register: managed_identity_output

    - name: Display managed identity details
      debug:
        var: managed_identity_output

    - name: Set User Identity Object ID
      shell: az identity show --name "${USER_ASSIGNED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP}" --query 'principalId' -o tsv
      register: identity_object_id

    - name: Display User Identity Object ID
      debug:
        var: identity_object_id

    - name: Set User Identity Client Identity
      shell: az identity show --name "${USER_ASSIGNED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP}" --query 'clientId' -o tsv
      register: identity_client_id

    - name: Display User Identity Client ID
      debug:
        var: identity_client_id