---
- hosts: localhost
  connection: local
  vars:
    SUBSCRIPTION: 9dc2c3d2-35a8-4370-8997-b56a57b5778d
    CLIENT_ID: 807252b3-8c49-4304-8371-9d99afa9dbac
    PASSWORD: hFO8Q~Qp3LjBGHR_sikE0-s2u2ds5tWMyy6~3bTt
    TENANT: redhat0.onmicrosoft.com
  tasks:
    - name: login to AZ cli 
      shell: az login --service-principal --username "{{ CLIENT_ID }}" --password "{{ PASSWORD }}" --tenant "{{ TENANT }}"

    - name: Get OIDC Issuer using az cli
      shell: az aro show --name aro-mid --resource-group aro-rg --query clusterProfile.oidcIssuer --output tsv
      register: oidc_results

    - name: Get keyvault principal using az cli
      shell: az identity show --name example-user-assigned-identity --resource-group aro-rg --query 'principalId' -o tsv
      register: kv_principal_results

    - name: Display OIDC
      debug:
        var: kv_principal_results.stdout_lines