---
- hosts: localhost
  connection: local

  tasks:
    - name: Get OIDC Issuer using az cli
      command: "/usr/local/bin/az aro show --name aro-mid --resource-group aro-rg --query clusterProfile.oidcIssuer --output tsv"