---
- hosts: localhost
  connection: local

  tasks:
    - name: login to AZ cli 
      shell: az login --service-principal --username "{{ CLIENT_ID }}" --password "{{ PASSWORD }}" --tenant "{{ TENANT }}"

    - name: Get OIDC Issuer using az cli
      shell: az aro show --name aro-mid --resource-group aro-rg --query clusterProfile.oidcIssuer --output tsv
      register: oidc_results

    - name: Get keyvault principal using az cli
      shell: az identity show --name example-user-assigned-identity --resource-group aro-rg --query 'principalId' -o tsv
      register: kv_principal_results

    - name: Display OIDC
      debug:
        var: kv_principal_results.stdout_lines