---
- name: Create Azure User-Assigned Managed Identity
  hosts: localhost
  connection: local
  vars:
    resource_group_name: aro-rg
    #location: eastus
    identity_name: Identities
    #identity_name: UserAssignedIdentity
  tasks:
    - name: Query AZ Resources
      azure.azcollection.azure_rm_resource_info:
        resource_group: "{{ resource_group_name }}"
        provider: ManagedIdentity
        resource_type: userAssignedIdentities
        #resource_name: "{{ res_name }}"
        #location: "{{ location }}"
        #state: present
        api_version: "2024-11-30"
      register: managed_identity_output

    - name: Display managed identity details
      debug:
        var: managed_identity_output